/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"
#include "stm32f446xx_gpio_driver.h"
#include "stm32f446xx_uart_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void hardware_setup(void){
	/*
	 * ========================================
	 * 		    Clock Configuration
	 * ========================================
	 */
	GPIOA_PCLK_EN();

	/*
	 * ========================================
	 * 		PA5 (Red) Configuration
	 * ========================================
	 */
	GPIO_Handle_t LED_RED;

	LED_RED.pGPIOx = GPIOA;

	LED_RED.GPIO_PinConfig.GPIO_PinNumber = 5;
	LED_RED.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	LED_RED.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP; // Push Pull (default)
	LED_RED.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD; // the voltage output will be locked by STM32
															   // It will NOT float even without pull-up resistors
	LED_RED.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;

	GPIO_Init(&LED_RED);

	/*
	 * ========================================
	 * 		PA6 (Green) Configuration
	 * ========================================
	 */
	GPIO_Handle_t LED_GREEN;

	LED_GREEN.pGPIOx = GPIOA;

	LED_GREEN.GPIO_PinConfig.GPIO_PinNumber = 6;
	LED_GREEN.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	LED_GREEN.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP; // Push Pull (default)
	LED_GREEN.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD; // the voltage output will be locked by STM32
															   // It will NOT float even without pull-up resistors
	LED_GREEN.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;

	GPIO_Init(&LED_GREEN);
	/*
	 * ========================================
	 * 		PA7 (Blue) Configuration
	 * ========================================
	 */
	GPIO_Handle_t LED_BLUE;

	LED_BLUE.pGPIOx = GPIOA;

	LED_BLUE.GPIO_PinConfig.GPIO_PinNumber = 7;
	LED_BLUE.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	LED_BLUE.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP; // Push Pull (default)
	LED_BLUE.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD; // the voltage output will be locked by STM32
															   // It will NOT float even without pull-up resistors
	LED_BLUE.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_MEDIUM;

	GPIO_Init(&LED_BLUE);
}

int main(void)
{
	hardware_setup();
	GPIO_WriteToOutputPin(GPIOA, 5, ENABLE);
	GPIO_WriteToOutputPin(GPIOA, 6, ENABLE);
	GPIO_WriteToOutputPin(GPIOA, 7, ENABLE);
}
